### ISSUE TITLE
[Feature]: Bang-Bang problem template

### ISSUE THREAD

**Issue by hongyehu** [kestrelquantum/QuantumCollocation.jl#133]
### Feature Description

In some quantum systems, it is preferred to have bang-bang-like protocols with sparse gradient, and maybe also penalization on the absolute value of gradient to enforce a finite pulse gradient. If that problem template can be added, that is great! 

### Importance

5 (highest)

### What does this feature affect?

- [ ] quantum system construction
- [X] problem setup
- [ ] problem solution
- [ ] problem performance
- [ ] solution analysis
- [ ] plotting
- [ ] documentation
- [ ] tests
- [ ] other (please specify below)

**Comment by andgoldschmidt** [comment]
Closed by #136, at `src/problem_templates/unitary_bang_bang_problem.jl`
